export const Data = [{
    id: 1,
    name: 'Fizz',
    description: 'An effervescent fruity experience with hints of grape and coriander',
    maxquantity: '90',
    instock: '10',
    imageurl: 'https://mir-s3-cdn-cf.behance.net/project_modules/hd/2f681067522271.5b3cb6db2e669.jpg',
  },
  {
    id: 2,
    name: 'Pop',
    description: 'An explosion of flavor that will knock your socks off!',
    maxquantity: '90',
    instock: '10',
    imageurl: 'https://res.cloudinary.com/wnotw/images/c_limit,w_1536,q_auto:good,f_auto/v1605652028/npmum5kybg05zizjxykh/soda-can-design',
  },
  {
    id: 3,
    name: 'Cola',
    description: 'A basic no nonsense cola that is the perfect pick me up for any occasion',
    maxquantity: '190',
    instock: '10',
    imageurl: 'https://cdn.dribbble.com/users/660474/screenshots/2888374/cansoda.jpg',
  },
  {
    id: 4,
    name: 'Mega Pop',
    description: 'So flavorful and so invigorating, it should probably be illegal.',
    maxquantity: '40',
    instock: '10',
    imageurl: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/999ab567522271.5b3cb6db2fbf6.jpg',
  },
];